### ISSUE TITLE
Gt-Ac5300 Hnd 2.13 SS插件异常

### ISSUE THREAD

**Issue by eastyang11** [SURFBOARD-ONE/fancyss#14]
亲爱的技术大咖
 首先感谢在新版本2.13解决了以往无法订阅更新及识别V2节点的问题，这极大的缓解了遇到的首要可用问题。

但同时有发现目前的2.13版本无法支持Grpc协议的问题，请问可否在下个版本兼容它呢？

期待你的友善

**Comment by Auroraxpm** [comment]
Grpc項目已被砍詳情請參考V2ray,xray官方文檔

**Comment by eastyang11** [comment]
> Grpc项目已被砍详情请参考V2ray,xray官方文档
尽管对目前结果表示遗憾，但还是感谢您的友善回复。

如果方便还是期望您及优秀的团队可以在后续版本支持Grpc。愿幸福安康！
