### ISSUE TITLE
AX86U使用386.4固件无法正常工作并且CPU占用率100%

### ISSUE THREAD

**Issue by sao321** [SURFBOARD-ONE/fancyss#3]
不知道有没有人能复现这个问题。我尝试了fancyss和群里魔改的1.9.8均会有下图的问题
![1](https://user-images.githubusercontent.com/59861512/148938619-3c13c9ae-ea5d-4cfe-bbe7-0beffd370e7e.jpg)
（双清+仅安装科学插件，应该没有其它干扰因素）

但是群里有其它AX86U用户反馈没有遇到这种情况……

如果是个例请无视我，如果不是的话希望有解决方案。
感谢！

**Comment by sorachan123** [comment]
根据群里反馈，是由于386.4将jitterentropy-rngd改用为haveged造成的，不知作者大佬能否将插件兼容？

**Comment by dickding** [comment]
最新的2.06版解决这个问题了

**Comment by sorachan123** [comment]
> 最新的2.06版解决这个问题了

图上就是就是2.0.6…

**Comment by Auroraxpm** [comment]
没设备没法测试

**Comment by dickding** [comment]
我用的ax86u，386.4梅林，用了这个2.06版，正常使用。CPU占用没问题。Trojan节点正常工作，v2ray和ss没有节点，没法试。

**Comment by sorachan123** [comment]
> 没设备没法测试

感谢大佬回复，群里有人怀疑是由于ASUSWRT将jitterentropy改成haveged造成的，我也不知道是不是这个原因，大佬从技术角度上看有可能吗？

**Comment by sorachan123** [comment]
> 我用的ax86u，386.4梅林，用了这个2.06版，正常使用。CPU占用没问题。Trojan节点正常工作，v2ray和ss没有节点，没法试。

我是vless+ws+tls，但群里有人说他也是这样却没问题，我也不知道怎么排除其它可能性了…

**Comment by sora159** [comment]
根据SNB论坛那边的讨论，貌似386.4使用的dnsmasq 2.86有无限循环BUG（参考：https://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2022q1/016073.html），这个BUG会导致CPU使用率100%……

暂时不知道我碰到的问题是否是这个原因导致。

没有碰到问题的，请尝试将附加功能中“替换为dnsmasq-fastlookup“选择为”不替换“看看会不会碰到这个问题。

**Comment by dickding** [comment]
我这默认就是 “不替换”，没有问题的。

**Comment by sao321** [comment]
> 我这默认就是 “不替换”，没有问题的。

已经有多个用户遇到CPU占用100%的问题，我这应该不是个例。具体原因到底是dnsmasq 2.86还是haveged就不清楚了。

**Comment by final999** [comment]
默认 “不替换”没有问题的，如果选1或2都会出错。

**Comment by Cold98** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
