### ISSUE TITLE
2.1.6版本在ac68u上trojan不能使用

### ISSUE THREAD

**Issue by inthesun29** [SURFBOARD-ONE/fancyss#5]
![S20116-21281192(1)](https://user-images.githubusercontent.com/36074967/149662516-80169358-7bb9-4cfa-906e-1d9c20b5eb10.png)

![S20116-21275315(1)](https://user-images.githubusercontent.com/36074967/149662607-5d1dd6f8-7ba2-453e-8a3e-7dc2b8f287b0.png)
2.1.6版本在ac68u上，trojan不能使用，貌似trojan没有运行

**Comment by Auroraxpm** [comment]
> ![S20116-21281192(1)](https://user-images.githubusercontent.com/36074967/149662516-80169358-7bb9-4cfa-906e-1d9c20b5eb10.png)
> 
> ![S20116-21275315(1)](https://user-images.githubusercontent.com/36074967/149662607-5d1dd6f8-7ba2-453e-8a3e-7dc2b8f287b0.png) 2.1.6版本，木馬不能使用，貌似木馬在沒有運行

更新插件

**Comment by Auroraxpm** [comment]
> ![S20116-21281192(1)](https://user-images.githubusercontent.com/36074967/149662516-80169358-7bb9-4cfa-906e-1d9c20b5eb10.png)
> 
> ![S20116-21275315(1)](https://user-images.githubusercontent.com/36074967/149662607-5d1dd6f8-7ba2-453e-8a3e-7dc2b8f287b0.png) 2.1.6版本，木馬不能使用，貌似木馬在沒有運行

更新插件

**Comment by inthesun29** [comment]
> 更新插件

非常感谢，2.1.8新版插件已经可以在386版本的AC68U上正常工作了。
