### ISSUE TITLE
2.1.0存在bug

### ISSUE THREAD

**Issue by Bit-Geek** [SURFBOARD-ONE/fancyss#7]
国外连接有时连接不上，youtube能进入网页但是无法播放视频，Google有时搜索无法使用

**Comment by Auroraxpm** [comment]
更新规则 换DNS 清DNS缓存

**Comment by Bit-Geek** [comment]
> 

我都做过了，后来我是重新添加节点解决了这个问题，和dns应该没有关系，另外我用的是rtax88u，固件386.3.2和386.4.0都试过均存在这个问题，我的2.1.0是从2.0.9直接升级过来的
